name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' 
      
      - name: Instalar dependências
        run: |
          cd Sistema_Solar/Sistema_Solar_3D
          npm install
      
      - name: Build do projeto
        run: |
          cd Sistema_Solar/Sistema_Solar_3D
          npm run build # Certifique-se de que este script existe no seu package.json
      
      - name: Rodar os testes
        run: |
          cd Sistema_Solar/Sistema_Solar_3D
          npm test
      
      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Sistema_Solar/build 
          force_orphan: true